import type { Metadata } from "next";
import { Poppins } from "next/font/google";
import "./globals.scss";
import GdprContextProvider from "@/components/gdpr/GdprContext";
import { Nav, Footer } from "@/components/navigation";
import { checkTypes, checkUser } from "@/lib/handleUser";

const poppins = Poppins({
  weight: ["100", "300", "400", "500"],
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <GdprContextProvider>
        <body className={poppins.className}>
          <Nav />
          {children}
          <Footer />
        </body>
      </GdprContextProvider>
    </html>
  );
}
